name: Regression Guardrails

on:
  pull_request:
    branches: [ main, realtime-model-list-improvements ]
    paths:
      - 'extensions/claude-throne/webview/main.js'
      - 'extensions/claude-throne/src/views/PanelViewProvider.ts'
      - 'extensions/claude-throne/src/services/AnthropicApply.ts'
      - 'extensions/claude-throne/src/schemas/**'
      - 'tests/**'
      - 'extensions/claude-throne/tests/**'

jobs:
  label-check:
    name: Area Label Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for area labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const areaLabels = labels.filter(l => l.startsWith('area:'));
            
            const requiredAreas = [
              'area:model-selection',
              'area:provider',
              'area:proxy',
              'area:webview',
              'area:config'
            ];
            
            if (areaLabels.length === 0) {
              core.setFailed(
                'PR must have at least one area label: ' + requiredAreas.join(', ')
              );
            }
            
            console.log('Area labels found:', areaLabels);

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test
        env:
          CI: true

  extension-tests:
    name: Extension Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install extension dependencies
        working-directory: extensions/claude-throne
        run: npm ci
      
      - name: Compile extension
        working-directory: extensions/claude-throne
        run: npm run compile
      
      - name: Run extension tests
        working-directory: extensions/claude-throne
        run: npm test
        env:
          CI: true
      
      - name: Check for TypeScript errors
        working-directory: extensions/claude-throne
        run: npx tsc --noEmit

  contract-validation:
    name: Contract Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run contract tests
        run: npm test -- tests/contract.test.js
        env:
          CI: true
      
      - name: Validate schemas
        working-directory: extensions/claude-throne
        run: |
          echo "Checking schema exports..."
          node -e "
            const schemas = require('./src/schemas/messages.ts');
            const config = require('./src/schemas/config.ts');
            console.log('✅ Schema modules load successfully');
          "

  constitution-compliance:
    name: Constitution Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check guarded files
        id: check_files
        run: |
          echo "Checking for changes to Constitution-guarded files..."
          
          GUARDED_FILES=(
            "extensions/claude-throne/webview/main.js"
            "extensions/claude-throne/src/views/PanelViewProvider.ts"
            "extensions/claude-throne/src/services/AnthropicApply.ts"
          )
          
          CHANGED_GUARDED=0
          for file in "${GUARDED_FILES[@]}"; do
            if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "^$file$"; then
              echo "⚠️  Guarded file modified: $file"
              CHANGED_GUARDED=1
            fi
          done
          
          echo "changed_guarded=$CHANGED_GUARDED" >> $GITHUB_OUTPUT
      
      - name: Require test updates for guarded files
        if: steps.check_files.outputs.changed_guarded == '1'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const testFiles = files.filter(f => 
              f.filename.includes('test') || f.filename.includes('spec')
            );
            
            if (testFiles.length === 0) {
              core.setFailed(
                '⚠️  Constitution violation: Guarded files modified without test updates.\n' +
                'Files in webview/main.js, PanelViewProvider.ts, or AnthropicApply.ts require test coverage.'
              );
            }

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run smoke test
        run: |
          if [ -f "scripts/smoke.sh" ]; then
            bash scripts/smoke.sh
          else
            echo "Smoke test script not found, skipping"
          fi
        env:
          CI: true
